version: 2
jobs:
  validate:
    docker:
      - image: hashicorp/packer:1.1.1
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: Validate base
          command: packer validate ./packer-scripts/test.packer
  build-base:
    docker:
      - image: hashicorp/packer:1.1.1
    working_directory: ~/packer
    steps:
      - checkout
      - attach_workspace:
          at: ~/packer
      - run:
          name: Build base
          command: packer build ./packer-scripts/test.packer
          no_output_timeout: 30m
workflows:
  version: 2
  validate-and-build:
    jobs:
      - validate
      - build-base:
          requires:
            - validate
