version: 2
jobs:
  build-base:
    docker:
      - image: hashicorp/packer:1.1.1
    working_directory: ~/packer
    steps:
      - checkout
      - attach_workspace:
          at: ~/packer
      - run:
          name: Build base
          command: packer build ./packer-scripts/test.packer
          no_output_timeout: 30m
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-base
